export const lipsum = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque arcu augue, ultricies et tellus vitae, rutrum consectetur mi. Nulla laoreet eleifend odio a malesuada. Morbi sed semper nulla, id vestibulum felis. Donec vulputate, odio ac faucibus vestibulum, ipsum nibh pretium purus, vel placerat mauris ante sed sem. Etiam ornare magna arcu, eu molestie lectus iaculis eu. Integer sed lacus varius, cursus mi vitae, vehicula nibh. Proin ac ultricies arcu. Proin non ligula sit amet erat auctor aliquam non rhoncus quam.

Donec convallis condimentum aliquet. Nam vitae dignissim risus. Vestibulum vitae magna quis mi rhoncus vestibulum. Maecenas rutrum nulla ac est pulvinar, et blandit mauris bibendum. Nam iaculis erat diam, sit amet elementum sem varius ac. Suspendisse quis eros nisl. In at ante finibus nulla tempus blandit. Praesent sed dolor efficitur, pulvinar risus vel, maximus metus. Curabitur sagittis viverra felis vel imperdiet. Nunc eleifend convallis tellus vel varius. Maecenas lobortis sagittis diam, ac tristique nibh semper nec. Phasellus eu dolor et eros ultricies eleifend. Morbi dictum enim a velit consequat tincidunt.

Vestibulum velit arcu, tristique non tincidunt eu, condimentum vitae sem. Morbi eget bibendum nulla. Maecenas pellentesque, justo at luctus lobortis, mi velit sollicitudin velit, in eleifend nibh arcu quis lorem. Nullam nulla mauris, bibendum et arcu et, lacinia eleifend justo. Curabitur urna ipsum, rutrum sit amet semper et, facilisis ac urna. Vivamus ac dolor nec lorem vulputate varius sed maximus leo. Donec urna lacus, gravida a ipsum quis, mollis rhoncus elit.

Pellentesque condimentum velit vitae semper convallis. Integer venenatis ac libero viverra facilisis. Donec luctus purus eget mi sodales pharetra. Duis faucibus bibendum sem. Vivamus aliquam ipsum lacinia magna tincidunt, id volutpat dolor semper. Mauris quis quam at mi aliquam suscipit vel ut risus. Duis cursus nisi et hendrerit placerat.

Curabitur quis condimentum quam. Duis non condimentum turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin placerat quis sapien et fringilla. Integer a quam tellus. Pellentesque malesuada euismod neque et dignissim. Donec vel leo eget enim placerat malesuada. Cras ornare tincidunt fermentum. Praesent magna arcu, tempor non faucibus at, tincidunt id turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Fusce lacinia diam id dolor gravida, vel consequat lorem ultricies. Pellentesque vel est sed lorem maximus laoreet ut id neque. Ut vitae quam non orci finibus porttitor. Fusce vulputate non sem sit amet tristique. Etiam sed metus quis elit suscipit gravida semper sit amet nulla.
`;